name: 'dbt_models'
version: '0.1.0'

profile: 'dbt_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_models:
    staging:
      +schema: staging
      +materialized: view
      +grants: {'select': ['metabase']}
    analytics:
      +schema: analytics
      +materialized: table
      +grants: {'select': ['metabase']}

tests:
  +store_failures: true
  +schema: dbt_tests

on-run-end:
  - "{% for schema in schemas %}grant usage on schema {{ schema }} to reporter;{% endfor %}"