name: 'dbt_models'
profile: 'dbt_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_models:
    duckdb:
      +materialized: external
    postgres:
      admin:
        +schema: admin
        +materialized: table
        +grants: {'select': ['evidence', 'hex', 'metabase']}
      staging:
        +schema: staging
        +materialized: view
        +grants: {'select': ['evidence', 'hex', 'metabase']}
      analytics:
        +schema: analytics
        +materialized: table
        +grants: {'select': ['evidence', 'hex', 'metabase']}
  dbt_artifacts:
    +database: prod
    +schema: admin
    staging:
      +database: prod
      +schema: admin
    sources:
      +database: prod
      +schema: raw_dbt

data_tests:
  +store_failures: true
  +schema: dbt_tests

flags:
  source_freshness_run_project_hooks: True

on-run-end:
  # Upload the results dbt_artifacts package when the target is prod
  - "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"
  # Re-run external models with an in-memory version of dbt-duckdb
  - "{% if target.name in ['prod_duckdb', 'dev_duckdb'] %}{{ register_upstream_external_models() }}{% endif %}"
