name: 'dbt_models'
profile: 'dbt_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: external

data_tests:
  +store_failures: true
  +schema: dbt_tests

flags:
  source_freshness_run_project_hooks: True

vars:
  dbt_artifacts_s3_root: s3://data-lake-chodera

on-run-end:
  # Upload the results dbt_artifacts package when the target is prod (postgres or duckdb)
  - "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"
  # Re-run external models with an in-memory version of dbt-duckdb
  - "{% if target.name in ['prod', 'dev'] %}{{ register_upstream_external_models() }}{% endif %}"
