name: 'dbt_models'
version: '0.1.0'

profile: 'dbt_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_models:
    admin:
      +schema: admin
      +materialized: table
      +grants: {'select': ['evidence', 'hex', 'metabase']}
    staging:
      +schema: staging
      +materialized: view
      +grants: {'select': ['evidence', 'hex', 'metabase']}
    analytics:
      +schema: analytics
      +materialized: table
      +grants: {'select': ['evidence', 'hex', 'metabase']}
  dbt_artifacts:
    +database: prod
    +schema: admin
    staging:
      +database: prod
      +schema: admin
    sources:
      +database: prod
      +schema: raw_dbt

data_tests:
  +store_failures: true
  +schema: dbt_tests

flags:
  source_freshness_run_project_hooks: True

on-run-end:
  - "{% for schema in schemas %}grant usage on schema {{ schema }} to reporter;{% endfor %}"
  - "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"
