dbt_models:
  target: dev
  outputs:
    dev:
      type: duckdb
      external_root: s3://data-lake-chodera/dbt_models/dev
      extensions:
        - httpfs
        - parquet
      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

    prod:
      type: duckdb
      external_root: s3://data-lake-chodera/dbt_models/prod
      schema: analytics
      threads: 16
      path: md:prod?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}
      extensions:
        - httpfs
        - parquet
      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

    ci:
      type: duckdb
      external_root: "{{ env_var('CI_DUCKDB_EXTERNAL_ROOT') }}"
      threads: 4
      extensions:
        - httpfs
        - parquet
        - postgres
      secrets:
        - type: s3
          region: "{{ env_var('AWS_REGION') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
