name: Lint Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"

      - name: Install SQLFluff
        run: "pip install sqlfluff==2.3.4"

      - name: Get changed files
        id: get_changed_files
        run: |
          git fetch origin main
          main_sha=$(git rev-parse origin/main)
          echo "changed_files=$(git diff --diff-filter=d --no-commit-id --name-only -r $main_sha... | grep "\.sql$")" >> $GITHUB_OUTPUT

      - name: Lint dbt models
        if: steps.get_changed_files.outputs.changed_files != ''
        run: |
          echo "Linting:" ${{ steps.get_changed_files.outputs.changed_files }}
          sqlfluff lint ${{ steps.get_changed_files.outputs.changed_files }} --ignore templating
